version: 2
jobs:
  one:
    docker:
      - image: cimg/ruby:3.0.2
        auth:
        username: sakshibarbade
        password: githubpassword@15
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workplace 
      - run: echo "Trying out workplaces" > my_workplace/echo-output
      - persist_to_workplace:
        root: my_workplace
        paths:
          -echo-output
  two:
    docker:
      - image: cimg/ruby:3.0.2
        auth:
         username: sakshibarbade
         password: githubpassword@15
    steps:
      - checkout
      - run: echo "A more familiar hi"
      -attach_workplace:
         at: my_workplace
      - run: 
         if [[ $(cat my_workplace/echo-output) == "Trying out workspaces" ]]; then
           echo "It worked!";
         else
           echo "Nope!"; exit 1
           fi
          
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
